baseurl: 'https://yusuke.cloud'
title: Yusuke Ohashi
theme: PaperMod
languagecode: en
defaultcontentlanguage: en
enableEmoji: false
enableRobotsTXT: true
ignoreFiles:
  - \.gitignore$
  - ^README.md$
pagination:
  pagerSize: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
googleAnalytics: G-BYJK9D038N

buildDrafts: false
buildFuture: false
buildExpired: false

permalinks:
  posts: /:sections[1:]/:slug/

minify:
  disableXML: true
  minifyOutput: true

params:
  author: Yusuke Ohashi
  info: 'iOS Developer, DevOps, Blogger, and Gamer'
  description: Yusuke Ohashi's personal website
  keywords: ["blog", "developer", "personal"]
  avatarurl: 'https://www.gravatar.com/avatar/6c1aa726eee0183a8820a97a515eb3ab?s=200'
  favicon_32: /img/favicon-32x32.png
  favicon_16: /img/favicon-16x16.png
  footercontent: Welcome to my personal website!
  displayFullLangName: true
  hidecredits: true
  hidecopyright: false
  ShowShareButtons: true
  hideSummary: true
  rtl: false
  math: true
  # customCSS:
  #   - css/gistfix.css
  colorscheme: auto
  images:
    - 'https://cdn.yusuke.cloud/assets/image/golden-gate-bridge.jpg'

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog
  
  utterances:
    repo: junkpiano/yusuke.cloud
    issueTerm: pathname
  social: true
  socialIcons:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 2
      url: 'https://github.com/junkpiano/'
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 3
      url: 'https://gitlab.com/junkpiano/'
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 1
      url: 'https://twitter.com/junkpiano/'
    - name: Linkedin
      icon: fa fa-linkedin fa-2x
      weight: 4
      url: 'https://www.linkedin.com/in/yusukeohashi'
    - name: Mastodon
      icon: fa fa-mastodon fa-2x
      weight: 5
      url: 'https://mastodon.technology/@junkpiano'
      rel: me
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    LanguageName: ':us:'
    contentDir: content/english
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Posts
          weight: 2
          url: /posts/
        - name: RSS
          weight: 3
          url: /index.xml
        - name: TIL
          weight: 4
          url: https://til.yusuke.cloud
        - name: nostr
          weight: 5
          url: https://nostr.yusuke.cloud
  ja:
    LanguageName: ':jp:'
    contentDir: content/japanese
    footercontent: 楽しんでいってね。
    params:
      info: 'iOS 開発者, DevOps, ブロガー, ゲーマー'
    menu:
      main:
        - name: ホーム
          url: /
          weight: 1
        - name: 記事
          weight: 2
          url: /posts/
        - name: 購読
          weight: 3
          url: /ja/index.xml
        - name: 学び
          weight: 4
          url: https://til.yusuke.cloud
        - name: nostr
          weight: 5
          url: https://nostr.yusuke.cloud
