baseurl = "https://yusuke.cloud"
title = "Yusuke Ohashi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = false

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"
googleAnalytics = "UA-38557572-5"
  
[params]
    author = "Yusuke Ohashi"
    info = "iOS Developer, DevOps, Blogger, and Gamer"
    description = "Yusuke Ohashi's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "https://www.gravatar.com/avatar/6c1aa726eee0183a8820a97a515eb3ab?s=200"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    footercontent = "Welcome to my personal website!"
    hidecredits = true
    hidecopyright = false
    rtl = false
    math = true
    custom_css = []
    colorscheme = "auto"

    [params.utterances]
        repo = "junkpiano/yusuke.cloud"
        issueTerm = "pathname"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 2
    url = "https://github.com/junkpiano/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    weight = 3
    url = "https://gitlab.com/junkpiano/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/junkpiano/"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/yusukeohashi"

# Menu links
[languages.en]
languageName = ":uk:"
contentDir = "content/english"

[[languages.en.menu.main]]
  name = "Home"
  pre = "home"
  url = "/"
  weight = 1
[[languages.en.menu.main]]
  name = "About"
  weight = 2
  url  = "/about/"
[[languages.en.menu.main]]
  name = "Posts"
  weight = 3
  url  = "/posts/"
[[languages.en.menu.main]]
  name = "RSS"
  weight = 4
  url  = "/index.xml"

[languages.ja]
languageName = ":jp:"
contentDir = "content/japanese"
footercontent = "楽しんでいってね。"

[languages.ja.params]
info = "iOS 開発者, DevOps, ブロガー, ゲーマー"

[[languages.ja.menu.main]]
  name = "ホーム"
  url = "/"
  weight = 1
[[languages.ja.menu.main]]
  name = "これは何？"
  weight = 2
  url  = "/about/"
[[languages.ja.menu.main]]
  name = "記事"
  weight = 3
  url  = "/posts/"
[[languages.ja.menu.main]]
  name = "購読"
  weight = 4
  url  = "/ja/index.xml"
